name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        # Can't use bun install until it respects yarn.lock package versions
        # run: bun install
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable
      - name: Check prettification
        run: |
          bun run pretty-check || \
          (bun run pretty-print --loglevel=silent \
          && git --no-pager diff \
          && exit 1)
