name: Website

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'website/**'
  push:
    branches: [main]
    paths:
      - 'website/**'

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  build_only:
    if: github.event_name != 'push' && github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        # Can't use bun install until it respects yarn.lock package versions
        # run: bun install
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable
      - name: Build packages
        run: bun run build
      - name: Build website
        run: bun run website:build

  build_and_publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        # Can't use bun install until it respects yarn.lock package versions
        # run: bun install
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable
      - name: Build packages
        run: bun run build
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_WEBSITE_DEPLOY }}
      - name: Deploy website to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email ${{ secrets.GH_PAGES_WEBSITE_PUBLISHER_EMAIL }}
          git config --global user.name ${{ secrets.GH_PAGES_WEBSITE_PUBLISHER_NAME }}
          bun run website:deploy
